# Generated by Django 3.2.3 on 2021-05-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_texxt',
            new_name='choice_text',
        ),
    ]
